// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api/prizes.ts";
import * as $2 from "./routes/api/prizes/[uuid].tsx";
import * as $3 from "./routes/api/winners.ts";
import * as $4 from "./routes/prizes/[prize].tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/prizes.ts": $1,
    "./routes/api/prizes/[uuid].tsx": $2,
    "./routes/api/winners.ts": $3,
    "./routes/prizes/[prize].tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
